seo: 
  site_name: Accelerate Sustainability
  title: Accelerate Sustainability - Curated Resources for the Sustainability Curious
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark_color: 'rgb(60,60,65)'
  medium_color: 'rgb(90,90,95)'
  light_color: '#F6F3F1'
  featured_color: '#F4A261'
  bold-featured_color: '#EC622B'
  dark-featured_color: '#1D5055'
